stages:
  - build-image
  - deploy

build_image:
  stage: build-image
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    - echo "$CI_COMMIT_TAG"
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
deploy:
  stage: deploy
  variables:
    DEPLOY_CURL_COMMAND: curl -X PUT "https://client-access-prod.sunteco.vn/spinner-management/v1/spinner/container/image" -H "accept:*/*" -H "Api-key:$SPINNER_TOKEN" -H "Content-Type:application/json" -d '{ "containerName":"$CONTAINER_NAME", "imageTag":"$CI_COMMIT_TAG", "spinnerUUID":"$SPINNER_UUID", "workspaceUUID":"$WORKSPACE_UUID" }'
  script:
    - echo "start update image $CI_REGISTRY_IMAGE $SPINNER_UUID $WORKSPACE_UUID"
    - echo "$DEPLOY_CURL_COMMAND"
    - 'eval "$DEPLOY_CURL_COMMAND"'
    - exit 0
